# -*- coding: utf-8 -*-
"""day1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xb5692EMBou9-BK5xYLKIiW_myd8bYzy
"""

import pandas as pd

df = pd.read_csv("student_performance.csv")
df['total_score'] = df['math_score'] + df['science_score'] + df['english_score'] + df['programming_score']

print("Lowest Math Score :", df['math_score'].min())
print("Average Math Score :", df['math_score'].mean())
print("Average Programming Score :", df['programming_score'].mean())
print("Average Attendance Percentage :", df['attendance_percentage'].mean())

avg_total_score_by_gender = df.groupby('gender')['total_score'].mean()
print("\nAverage Total Score by Gender:")
print(avg_total_score_by_gender)

print("\nTop 5 Performers based on Total Score:")
top_performers = df.sort_values(by='total_score', ascending=False).head(5)
print(top_performers[['name', 'department', 'total_score']])

print("\nAttendance Analysis (Students with attendance below 75%):")
low_attendance_students = df[df['attendance_percentage'] < 75]

if not low_attendance_students.empty:
    print(low_attendance_students[['name', 'department', 'attendance_percentage']])
else:
    print("All students have attendance above 75%.")

electronics_students_count = df[df['department'] == 'Electronics'].shape[0]
print(f"Number of students from the Electronics Department: {electronics_students_count}")

average_attendance_female = df[df['gender'] == 'Female']['attendance_percentage'].mean()
print(f"Average attendance of female students: {average_attendance_female:.2f}%")

students_high_attendance = df[df['attendance_percentage'] > 80]
average_programming_score_high_attendance = students_high_attendance['programming_score'].mean()
print(f"Average programming score for students with attendance above 80%: {average_programming_score_high_attendance:.2f}")

average_total_score_by_department = df.groupby('department')['total_score'].mean()
highest_average_department = average_total_score_by_department.idxmax()
highest_average_score = average_total_score_by_department.max()
print(f"Department with the highest average total score: {highest_average_department} (Average Score: {highest_average_score:.2f})")

students_low_scores = df[(df['math_score'] < 60) | (df['science_score'] < 60) | (df['english_score'] < 60) | (df['programming_score'] < 60)]

if not students_low_scores.empty:
    print("Students with at least one score below 60:")
    print(students_low_scores[['name', 'department', 'math_score', 'science_score', 'english_score', 'programming_score']])
else:
    print("No students have scored less than 60 in any subject.")