# -*- coding: utf-8 -*-
"""Day2MiniProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NjG_0_pzMcrB5gY9lM7Fui3jRgyWnJJ-
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import sqlite3
import matplotlib.pyplot as plt

# automatically get uploaded file name
filename = list(uploaded.keys())[0]

# read csv
df = pd.read_csv(filename)

# preview
print(df.head())

conn = sqlite3.connect("college.db")

# save dataframe to sqlite
df.to_sql("students", conn, if_exists="replace", index=False)

print("students table created")

q1 = """
SELECT department,
AVG(math_score) AS avg_math
FROM students
GROUP BY department
"""

df1 = pd.read_sql_query(q1, conn)
print(df1)

q2 = """
SELECT department,
COUNT(*) AS student_count
FROM students
GROUP BY department
"""

df2 = pd.read_sql_query(q2, conn)
print(df2)

q3 = """
SELECT name,
(math_score + science_score + english_score + programming_score) AS total_score
FROM students
ORDER BY total_score DESC
LIMIT 8
"""

df3 = pd.read_sql_query(q3, conn)
print(df3)

q4 = """
SELECT gender,
AVG(attendance_percentage) AS avg_attendance
FROM students
GROUP BY gender
"""

df4 = pd.read_sql_query(q4, conn)
print(df4)

fig, ax = plt.subplots(2,2, figsize=(12,8))

# Panel 1
ax[0,0].bar(df1["department"], df1["avg_math"])
ax[0,0].set_title("Avg Math by Department")

# Panel 2
ax[0,1].pie(
    df2["student_count"],
    labels=df2["department"],
    autopct="%1.1f%%"
)
ax[0,1].set_title("Student Count")

# Panel 3
ax[1,0].barh(df3["name"], df3["total_score"])
ax[1,0].set_title("Top 8 Students")

# Panel 4
ax[1,1].bar(df4["gender"], df4["avg_attendance"])
ax[1,1].set_title("Gender Avg Attendance")

plt.tight_layout()
plt.show()

query = """
SELECT AVG(programming_score) AS avg_programming
FROM students
WHERE gender='Female'
"""

print(pd.read_sql_query(query, conn))

query = """
SELECT *
FROM students
"""

result = pd.read_sql_query(query, conn)

print(result)

query = """
SELECT department,
AVG(attendance_percentage) AS avg_attendance
FROM students
GROUP BY department
HAVING AVG(attendance_percentage) > 85
"""

print(pd.read_sql_query(query, conn))

pd.read_sql_query(query, conn)

query = """
SELECT department,
AVG(programming_score) AS avg_programming
FROM students
GROUP BY department
"""

df_prog = pd.read_sql_query(query, conn)

plt.bar(df_prog["department"], df_prog["avg_programming"])
plt.title("Avg Programming by Department")
plt.show()
