# -*- coding: utf-8 -*-
"""day2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rNSFCpOQbOhrUsIEUSaY6B_jOyLVY1Op
"""

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
print("All libraries imported successfully")
print(f"pandas version: {pd.__version__}")
print(f"sqlite3 version: {sqlite3.version}")

df=pd.read_csv('student_performance.csv')

print(f"Dataset loaded: {df.shape[0]} students, {df.shape[1]} columns")
print(f"Columns:{df.columns.tolist()}")
print("\nFirst 3 rows:")
df.head(3)

conn=sqlite3.connect('college.db')
cursor=conn.cursor()
df.to_sql(
    'students',
    conn,
    index=False,
    if_exists='replace'
)
cursor.execute("SELECT COUNT(*) FROM students")
count=cursor.fetchone()[0]
print(f"Database 'college_db' created successfully")
print(f"Table 'students' has {count} rows")

cursor.execute("PRAGMA table_info(students)")
columns_info = cursor.fetchall()
print("Table structure of 'students':")
print(f"{'Column Name' :<25} {'Data Type' :<12}")
print("-" * 38)
for col in columns_info:
  print(f"{col[1]:<25} {col[2]:<12}")

def run_query(sql,description=""):
  if description:
    print(f"\n{'='*55}")
    print(f" {description}")
    print(f"{'='*55}")
  result=pd.read_sql_query(sql,conn)
  print(result.to_string(index=False))
  return result
print("Helper function 'run-query' defined successfully")
print("Usage:reun_query(sql_string,description_label")

query1="""
SELECT student_id,name,department,math_score,attendance_percentage
FROM students
LIMIT 10
"""
result1=run_query(query1,"Query 1:First 10 students(SELECT+LIMIT)")

query2="""
SELECT student_id,name,department,math_score,attendance_percentage
FROM students
ORDER BY student_id DESC
LIMIT 5
"""
result1=run_query(query1,"Query 2:Last 5 students(SELECT+LIMIT)")

query3="""
SELECT student_id,name,department,math_score,attendance_percentage
FROM students
ORDER BY math_score DESC
LIMIT 5
"""
result1=run_query(query1,"Query 2:Last 5 maths_score(SELECT+LIMIT)")

query1="""
SELECT student_id,name,department,programming_score
FROM students
WHERE programming_score BETWEEN 50 AND 75
ORDER BY student_id
"""
result1=run_query(query1,"Query 1:The List of students between 50 and 75")

query2="""
SELECT student_id,math_score,science_score,name,department,programming_score
FROM students
WHERE department='Computer Science'
ORDER BY programming_score DESC
"""
result1=run_query(query2,"Query")

query3="""
SELECT department From students
GROUP BY department
"""
result1=run_query(query3,"Query")

query_top_scorers = """
SELECT student_id, name, department, programming_score
FROM students
WHERE department IN ('Computer Science', 'Electronics', 'Mechanical')
ORDER BY programming_score DESC, department, name
LIMIT 1
"""
run_query(query_top_scorers, "Top programming scorer")

query_low_attendance = """
SELECT student_id, name, department, attendance_percentage
FROM students
WHERE attendance_percentage < 50
ORDER BY attendance_percentage DESC
"""
run_query(query_low_attendance, "Students with attendance percentage less than 50")

query3 = """
SELECT student_id, name, department, attendance_percentage, math_score, science_score, english_score, programming_score
FROM students
WHERE attendance_percentage >= 50
ORDER BY attendance_percentage DESC, name
"""
run_query(query3, "attendace")

import pandas as pd
import sqlite3
conn = sqlite3.connect('college.db')
dept_data={
    'dept_code':['CS','EC','ME','CE'],
    'dept_name':['Computer Science','Electronics','Mechanical','Civil'],
    'hod_name':['Dr.Sharma','Dr.Reddy','Dr.Patel','Dr.Kumar'],
    'established':[1990,1995,2000,2005],
    'intake':[60,60,60,60]
}
dept_df=pd.DataFrame(dept_data)
dept_df.to_sql('departments',conn,index=False,if_exists='replace')
print(dept_df.to_string(index=False))
dept_map={
    'CS':'Computer Science',
    'EC':'Electronics',
    'ME':'Mechanical',
    'CE':'Civil'
}
df['dept_code']=df['department'].map(dept_map)
df.to_sql('students',conn,index=False,if_exists='replace')
print("\nUpdated students list with deot_code column")

query_join="""
SELECT
s.name,
s.math_score,
d.dept_name,
d.hod_name,
d.established
FROM students s
INNER JOIN departments AS d ON s.dept_code=d.dept_code
ORDER BY s.math_score DESC
LIMIT 8
"""
result=run_query(query_join,"Query")

chart1_sql="""
SELECT department,ROUND(AVG(math_score),2) AS avg_math_score
FROM students
GROUP BY department
ORDER BY avg_math_score DESC
"""
chart1_data=pd.read_sql_query(chart1_sql,conn)
fig,ax=plt.subplots(figsize=(10,6))
ax.set_title('Average Math Score by Department')
ax.set_xlabel('Department')
ax.set_ylabel('Average Math Score')
plt.show()