# -*- coding: utf-8 -*-
"""day4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TyKN_IwJ87V8gDwdAeFbSYxhTZne_h-a
"""

!pip install pyspark --quiet
print('Pyspark installation complete!')

from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.functions import year,month,to_date,col,round as spark_round
import matplotlib.pyplot as plt
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
spark=SparkSession.builder\
.appName('Day4_BigData_Sales')\
.config('spark.sql.adaptive.enabled',True)\
.getOrCreate()
print(f"Spark version:{spark.version}")
print(f"SparkSession:ACTIVE")

df_bronze=spark.read\
.option('header','true')\
.option('InferSchema','true')\
.csv('large_sales_data.csv')
print('===BRONZE LAYER===')
print(f"Rows:{df_bronze.count()}")
print(f"Columns:{len(df_bronze.columns)}")
print(f"Names:{df_bronze.columns}")
print()
df_bronze.printSchema()

print('First 5 rows:')
df_bronze.show(5,truncate=False)
print("\nBasic statistics for numeric columns:")
df_bronze.select('quantity','unit_price','revenue').describe().show()

df_bronze.write \
.mode('overwrite') \
.parquet('sales_bronze.parquet')
print('Bronze Parquet saved: sales_bronze.parquet')

import os
def get_dir_size(path):
  """Get size of a file or directory in KB"""
  if os.path.isfile(path):
    return os.path.getsize(path) / 1024
  total=0
  for dirpath,dirnames,filenames in os.walk(path):
    for f in filenames:
      total +=os.path.getsize(os.path.join(dirpath,f))
  return  total / 1024
csv_size=get_dir_size('large_sales_data.csv')
parquet_size=get_dir_size('sales_bronze.parquet')
reduction=(1 - parquet_size/csv_size) * 100
print(f'CSV file size: {csv_size:.2f} KB')
print(f'Parquet file size: {parquet_size:.2f} KB')
print(f'Reduction in size: {reduction:.1f}% smaller')
print(f'At 1 TB scale:CSV=1000GB -> Parquet={1000*(1-reduction/100):0f} GB')

df_silver=df_bronze\
.dropDuplicates()\
.dropna(subset=['order_id','product','revenue'])
df_silver=df_silver.withColumn(
    'order_date',
    to_date(col('order_date'),'dd-MM-yyyy')
)
df_silver=df_silver\
.withColumn('order_year',year(col('order_date')))\
.withColumn('order_month',month(col('order_date')))
df_silver=df_silver.withColumn(
    'revenue_category',
    F.when(col('revenue')>40000,'High')
    .when(col('revenue')>10000,'Medium')
    .otherwise('Low')
)
print(f"Silver layer rows:{df_silver.count()}")
print("New columns added:order_year,order_month,revenue_category")
df_silver.select('product','revenue','order_year','order_month','revenue_category').show()

df_silver.write\
.mode('overwrite')\
.parquet('sales_silver.parquet')
print("Silver Parquet saved:sales_silver.parquet")
print(f"Silver size:{get_dir_size("sales_silver.parquet"):1f}KB")
df_verify=spark.read.parquet('sales_silver.parquet')
print('\n===Verify Silver layer===')
print(f"Read-back rows:{df_verify.count()} (should match silver count)")
df_verify.printSchema()