# -*- coding: utf-8 -*-
"""day3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KvRvECqaYRfSfcAoARH9Dl2io64SNor2
"""

import pandas as pd
import requests
import json
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')
print("Libraries imported successfully")
print(f"Pandas version: {pd.__version__}")
print(f"Requests version: {requests.__version__}")
print(f"Loaded at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

raw_df=pd.read_csv('messy_sales_data.csv')
print(f"Rows imported: {raw_df.shape[0]}")
print(f"Columns : {raw_df.shape[1]}")
print(f"Colums name:{raw_df.columns.tolist()}")
print("\nFirst five rows of raw data:")
raw_df.head()

print("="*55)
print("DATA QUALITY DIAGNOSIS REPORT")
print("="*55)
print("\n[1] MISSING VALUES per column")
print(raw_df.isnull().sum())
print(f"\n[2] DUPILCATE ROWS:{raw_df.duplicated().sum()}")
print(f"\n[3] DATA TYPES per column:\n")
print(raw_df.dtypes)
print("\n[4] UNIQUE CATEGORIES:",raw_df['category'].dropna().unique().tolist())
print("\n[5] SAMPLE ORDER DATES",raw_df['order_date'].unique()[:8].tolist())
print("\n[6] SAMPLE NAMES:",raw_df['customer_name'].dropna().unique()[:8].tolist())

df=raw_df.copy()
print(f"Working copy created with shape:{df.shape}")
print(f"raw_df is untouched.We can always reset with;df=raw_df.copy()")

print(f"Total missing values BEFORE fix:{df.isnull().sum().sum()}")
df['customer_name'].fillna('Unknown Customer',inplace=True)
median_qty=df['quantity'].median()
df['quantity'].fillna(median_qty,inplace=True)
print(f"Filled missing quantity with median value:{median_qty}")
df['category'].fillna('Uncategorized',inplace=True)
df['product'].fillna('Unknown Product',inplace=True)
print(f"Total missing values AFTER fix:{df.isnull().sum().sum()}")

print(f"DUPILCATE ROWS:{df.duplicated().sum()}")

print(f"Rows BEFORE deduplication:{len(df)}")
print(f"Duplicate rows found:{df.duplicated().sum()}")
duplicate_mask=df.duplicated(keep=False)
print("\nThe dupilcated rows(all copies shown):")
print(df[duplicate_mask][['order_id','customer_name','product','order_date']].to_string(index=True))
df.drop_duplicates(inplace=True)
df.reset_index(drop=True,inplace=True)
print(f"\nRows AFTER deduplication:{len(df)}")
print(f"Rows removed:{len(raw_df)-len(df)}")

print("Sample dates BEFORE parsing:")
print(df['order_date'].head(10).tolist())
df['order_date']=pd.to_datetime(df['order_date'],dayfirst=False,errors='coerce')
nat_mask=df['order_date'].isnull()
df.loc[nat_mask,'order_date']=pd.to_datetime(df.loc[nat_mask,'order_date'],dayfirst=True,errors='coerce')
nat_count=df['order_date'].isnull().sum()
print(f"\nUnparseable dates remaining(NaT):{nat_count}")
df['year']=df['order_date'].dt.year
df['month']=df['order_date'].dt.month
df['month_name']=df['order_date'].dt.strftime('%B')
df['day_name']=df['order_date'].dt.strftime('%A')
print("\nSample dates AFTER parsing:")
print(df[['order_date','year','month','month_name','day_name']].head(8).to_string(index=False))

print("Names BEFORE standardization:(sample):")
print(df['customer_name'].unique()[:8].tolist())
df['customer_name']=df['customer_name'].str.strip().str.title()
print("\nNames AFTER standardization:(sample):")
print(df['customer_name'].unique()[:8].tolist())

wrong_mask=(df['product']=='Keyboard')&(df['category']=='Electronics')
print(f"Rows to fix:{wrong_mask.sum()}")
print("Before Fix")
print(df[wrong_mask][['order_id','product','category']].to_string(index=False))
df.loc[wrong_mask,'category']='Accessories'
print("After fix:")
print(df[wrong_mask][['order_id','product','category']].to_string(index=False))
print("\nAll unique categories now:",sorted(df['category'].unique().tolist()))

df['quantity']=pd.to_numeric(df['quantity'],errors='coerce').astype(int)
df['unit_price']=pd.to_numeric(df['unit_price'],errors='coerce')
df['revenue']=df['quantity']*df['unit_price']
print("Revenue column created successfully.")
print("\nSample:quantity x unit_price=revenue")
print(df[['customer_name','product','quantity','unit_price','revenue']].head(8).to_string(index=False))

# ============================================================
# CELL 11 — Post-Cleaning Validation Report
# ============================================================


# Calculate the data quality score
# We check 5 things: no missing values, no duplicates, no date nulls, no revenue nulls
# Each passing check contributes 20 points (5 checks × 20 = 100)
missing_count   = df.isnull().sum().sum()
duplicate_count = df.duplicated().sum()
date_nulls      = df['order_date'].isnull().sum()
revenue_nulls   = df['revenue'].isnull().sum()


checks_passed   = sum([
    missing_count   == 0,   # 20 points
    duplicate_count == 0,   # 20 points
    date_nulls      == 0,   # 20 points
    revenue_nulls   == 0,   # 20 points
    len(df)         > 0     # 20 points (dataset is not empty)
])
quality_score = checks_passed * 20


# ── Print the report ─────────────────────────────────────────
print("=" * 55)
print("  POST-CLEANING VALIDATION REPORT")
print("=" * 55)
print(f"  Original rows   : {len(raw_df)}")
print(f"  Cleaned rows    : {len(df)}")
print(f"  Rows removed    : {len(raw_df) - len(df)} (duplicates)")
print(f"  Missing values  : {missing_count}")
print(f"  Duplicates      : {duplicate_count}")
print(f"  Date nulls      : {date_nulls}")
print(f"  Revenue nulls   : {revenue_nulls}")
print(f"  Columns total   : {len(df.columns)}")
print("=" * 55)
print(f"  DATA QUALITY SCORE : {quality_score}/100")
print(f"  DATA IS CLEAN      : {quality_score == 100}")
print("=" * 55)


# ── Actionable Debugging Suggestions ─────────────────────────
if missing_count > 0:
    print("\n  ACTION REQUIRED: Missing values detected.")
    print("  → Use df['column'].fillna(value, inplace=True)")
    print("  → For numbers: fillna(df['column'].median())")
    print("  → For text   : fillna('Unknown')")


if duplicate_count > 0:
    print("\n  ACTION REQUIRED: Duplicate rows detected.")
    print("  → Use df.drop_duplicates(inplace=True)")


if date_nulls > 0:
    print("\n  ACTION REQUIRED: Unparseable dates found.")
    print("  → Check for unusual date formats in the raw data")
    print("  → Use pd.to_datetime(col, dayfirst=True, errors='coerce')")


if quality_score == 100:
    print("\n  All checks passed. Data is ready for analysis.")

serp_api_key='656bbad74f275aae2e434511d384e22bee1a98ff0592830e79c8463733ea88e8'
SERP_URL='https://serpapi.com/search.json'
SEARCH_QUERY='Data Engineer India'
print(f"SerpAPI Key  : {'Set (live data)' if serp_api_key != 'YOUR_SERPAPI_KEY_HERE' else 'Not set (fallback data will be used)'}")
print(f"Search query:{SEARCH_QUERY}")

output_filename = 'clean_sales_data.csv'
df.to_csv(output_filename, index=False)
print(f"Cleaned data saved to: {output_filename}")
print(f"Final dataset: {df.shape[0]} rows x {df.shape[1]} columns")
print("\nETL Pipeline for Sales Data: COMPLETE")
print("EXTRACT    -> messy_sales_data.csv loaded")
print(" TRANSFORM -> 6 issues fixed (nulls, dupes, dates, names, categories, types)")
print(" LOAD      -> clean_sales_data.csv saved")

